[package]
cairo-version = "2.3.0"
name = "myapp"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.0.19" }

[[target.dojo]]
build-external-contracts = [
    "pixelaw::core::models::pixel::{pixel, Pixel, PixelUpdate}",
    "pixelaw::core::models::registry::{app, app_name, core_actions_address}",
    "pixelaw::core::models::permissions::{permissions}",
    "pixelaw::core::utils::{get_core_actions, Direction, Position, DefaultParameters}",
    "pixelaw::core::actions::{actions, IActionsDispatcher, IActionsDispatcherTrait}"
]

[tool.dojo]
initializer_class_hash = "0xbeef"

[scripts]
ready_for_deployment = "bash ./scripts/ready_for_deployment.sh"
initialize = "bash ./scripts/default_auth.sh"
upload_manifest = "bash ./scripts/upload_manifest.sh"
ready_for_deployment_zsh = "zsh ./scripts/ready_for_deployment.sh"
initialize_zsh = "zsh ./scripts/default_auth.sh"
upload_manifest_zsh = "zsh ./scripts/upload_manifest.sh"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# rpc_url = "https://<rpc-url>"

account_address = "0x1275bf6bbde224b361455d990c089bfb05a5711aa90ec7ccb3d4e0ee9265b4e"
private_key = "0x23ca81e30674f67a3cdbd8aec702aa2715c28f5ede99b360c4061f65e731fce"